apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-1
    labels:
       app: my-depo1
spec:
   replicas: 2
   selector:
     matchLabels:
          app: my-depo1
   template:
     metadata:
       labels:
         app: my-depo1
     spec:
       containers:
       - name: my-depo-container
         image: shyam156/e2e-project:latest
         ports:
         - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: my-service
    labels:
       app: my-depo1
spec:
  selector:
       app: my-depo1
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
  type: NodePort
